experiment_name: aaf_config_enhancements
random_seed: 1998
head_type: gaussian
dataset:
  type: image
  spec: aaf
training:
  accelerator: gpu
  batch_size: 128
  chkp_dir: chkp
  chkp_freq: 10
  num_epochs: 10
  precision: 16
  optimizer:
    type: adam_w
    kwargs:
      lr: 0.0001
      weight_decay: 0.001
  lr_scheduler:
    type: cosine_annealing
    kwargs:
      T_max: 10
      eta_min: 0
      last_epoch: -1
  beta_scheduler:
    type: cosine_annealing
    kwargs:
      beta_0: 0.5
      beta_1: 0.5
      last_epoch: -1
evaluation:
  num_trials: 1
  log_dir: logs
wandb: True
devices: [1]
num_trials: 1
