experiment_name: cce_procedure_reviews
random_seed: 1998
head_type: gaussian
dataset:
  type: text
  spec: reviews
training:
  accelerator: gpu
  batch_size: 256
  chkp_dir: chkp/reviews
  chkp_freq: 10
  max_epochs: 20
  min_epochs: 5
  precision: 16
  optimizer:
    type: adam_w
    kwargs:
      lr: 0.0001
      weight_decay: 0.00001
  lr_scheduler:
    type: cosine_annealing
    kwargs:
      T_max: 20
      eta_min: 0
      last_epoch: -1
evaluation:
  num_trials: 1
  log_dir: logs
wandb: True
backbone_type: DistilBertFrozen
early_stopping: True
