experiment_name: random_procedure_reviews_gaussian_last2layer
random_seed: 1998
head_type: gaussian
dataset:
  type: text
  spec: reviews
training:
  accelerator: gpu
  batch_size: 32
  chkp_dir: chkp
  chkp_freq: 5
  max_epochs: 20
  min_epochs: 5
  precision: bf16-mixed
  optimizer:
    type: adam_w
    kwargs:
      lr: 0.001
      weight_decay: 0.00001
  lr_scheduler:
    type: cosine_annealing
    kwargs:
      T_max: 20
      eta_min: 0
      last_epoch: -1
evaluation:
  num_trials: 1
  log_dir: logs
wandb: True
early_stopping: True
