_wandb:
    value:
        cli_version: 0.19.1
        m:
            - "1": metrics/nll
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": active_learning/kth_trial
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": dataset_sizes/train
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": dataset_sizes/test
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": dataset_sizes/unlabeled
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": metrics/mae
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": active_learning/iteration
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": metrics/rmse
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": metrics/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": dataset_sizes/val
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 103
                - 106
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 103
                - 106
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.10.15
            "5": 0.19.1
            "6": 4.44.2
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-arm64
